# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\program_diplom\designs\authenticate.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(639, 285)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelModel = QtWidgets.QLabel(self.centralwidget)
        self.labelModel.setGeometry(QtCore.QRect(10, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelModel.setFont(font)
        self.labelModel.setObjectName("labelModel")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(160, 10, 471, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonBrowseModel = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonBrowseModel.setObjectName("buttonBrowseModel")
        self.horizontalLayout.addWidget(self.buttonBrowseModel)
        self.textModelName = QtWidgets.QLineEdit(self.layoutWidget)
        self.textModelName.setObjectName("textModelName")
        self.horizontalLayout.addWidget(self.textModelName)
        self.buttonUploadModel = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonUploadModel.setObjectName("buttonUploadModel")
        self.horizontalLayout.addWidget(self.buttonUploadModel)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 70, 641, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.labelCountParams = QtWidgets.QLabel(self.centralwidget)
        self.labelCountParams.setGeometry(QtCore.QRect(10, 50, 171, 16))
        self.labelCountParams.setObjectName("labelCountParams")
        self.textCountParams = QtWidgets.QLabel(self.centralwidget)
        self.textCountParams.setGeometry(QtCore.QRect(190, 50, 47, 16))
        self.textCountParams.setObjectName("textCountParams")
        self.labelData = QtWidgets.QLabel(self.centralwidget)
        self.labelData.setGeometry(QtCore.QRect(10, 90, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelData.setFont(font)
        self.labelData.setObjectName("labelData")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(160, 100, 471, 25))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonBrowseDataFolder = QtWidgets.QPushButton(self.layoutWidget_2)
        self.buttonBrowseDataFolder.setObjectName("buttonBrowseDataFolder")
        self.horizontalLayout_2.addWidget(self.buttonBrowseDataFolder)
        self.textDataFileName = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.textDataFileName.setObjectName("textDataFileName")
        self.horizontalLayout_2.addWidget(self.textDataFileName)
        self.buttonUploadImages = QtWidgets.QPushButton(self.layoutWidget_2)
        self.buttonUploadImages.setObjectName("buttonUploadImages")
        self.horizontalLayout_2.addWidget(self.buttonUploadImages)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 150, 641, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.buttonAuthenticate = QtWidgets.QPushButton(self.centralwidget)
        self.buttonAuthenticate.setGeometry(QtCore.QRect(240, 190, 161, 23))
        self.buttonAuthenticate.setObjectName("buttonAuthenticate")
        self.labelDataUploaded = QtWidgets.QLabel(self.centralwidget)
        self.labelDataUploaded.setGeometry(QtCore.QRect(10, 130, 71, 16))
        self.labelDataUploaded.setObjectName("labelDataUploaded")
        self.textDataUploaded = QtWidgets.QLabel(self.centralwidget)
        self.textDataUploaded.setGeometry(QtCore.QRect(80, 130, 47, 16))
        self.textDataUploaded.setObjectName("textDataUploaded")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 639, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelModel.setText(_translate("MainWindow", "Модель"))
        self.buttonBrowseModel.setText(_translate("MainWindow", "Browse Model"))
        self.buttonUploadModel.setText(_translate("MainWindow", "Upload Browsed Model"))
        self.labelCountParams.setText(_translate("MainWindow", "Количество параметров модели:"))
        self.textCountParams.setText(_translate("MainWindow", "0"))
        self.labelData.setText(_translate("MainWindow", "Данные"))
        self.buttonBrowseDataFolder.setText(_translate("MainWindow", "Browse Data Folder"))
        self.buttonUploadImages.setText(_translate("MainWindow", "Upload Browsed Images"))
        self.buttonAuthenticate.setText(_translate("MainWindow", "Произвести аутентификацию"))
        self.labelDataUploaded.setText(_translate("MainWindow", "Загружены:"))
        self.textDataUploaded.setText(_translate("MainWindow", "Нет"))

