# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\program_diplom\designs\test.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(798, 321)
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 150, 801, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.labelTrainTitle = QtWidgets.QLabel(Form)
        self.labelTrainTitle.setGeometry(QtCore.QRect(20, 10, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTrainTitle.setFont(font)
        self.labelTrainTitle.setObjectName("labelTrainTitle")
        self.labelTrainCount = QtWidgets.QLabel(Form)
        self.labelTrainCount.setGeometry(QtCore.QRect(460, 10, 111, 21))
        self.labelTrainCount.setObjectName("labelTrainCount")
        self.textTrainCount = QtWidgets.QLineEdit(Form)
        self.textTrainCount.setGeometry(QtCore.QRect(570, 10, 51, 21))
        self.textTrainCount.setObjectName("textTrainCount")
        self.labelTestTitle = QtWidgets.QLabel(Form)
        self.labelTestTitle.setGeometry(QtCore.QRect(20, 170, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTestTitle.setFont(font)
        self.labelTestTitle.setObjectName("labelTestTitle")
        self.labelTestCount = QtWidgets.QLabel(Form)
        self.labelTestCount.setGeometry(QtCore.QRect(460, 170, 111, 21))
        self.labelTestCount.setObjectName("labelTestCount")
        self.textTestCount = QtWidgets.QLineEdit(Form)
        self.textTestCount.setGeometry(QtCore.QRect(570, 170, 51, 21))
        self.textTestCount.setObjectName("textTestCount")
        self.labelTrainCountAliens = QtWidgets.QLabel(Form)
        self.labelTrainCountAliens.setGeometry(QtCore.QRect(20, 100, 101, 16))
        self.labelTrainCountAliens.setObjectName("labelTrainCountAliens")
        self.labelTrainCountOurs = QtWidgets.QLabel(Form)
        self.labelTrainCountOurs.setGeometry(QtCore.QRect(20, 40, 101, 16))
        self.labelTrainCountOurs.setObjectName("labelTrainCountOurs")
        self.textTrainCountOurs = QtWidgets.QLineEdit(Form)
        self.textTrainCountOurs.setGeometry(QtCore.QRect(120, 40, 51, 20))
        self.textTrainCountOurs.setObjectName("textTrainCountOurs")
        self.textTrainCountAliens = QtWidgets.QLineEdit(Form)
        self.textTrainCountAliens.setGeometry(QtCore.QRect(120, 100, 51, 20))
        self.textTrainCountAliens.setObjectName("textTrainCountAliens")
        self.labelTrainOursError = QtWidgets.QLabel(Form)
        self.labelTrainOursError.setGeometry(QtCore.QRect(190, 40, 181, 16))
        self.labelTrainOursError.setObjectName("labelTrainOursError")
        self.textTrainOursError = QtWidgets.QLineEdit(Form)
        self.textTrainOursError.setGeometry(QtCore.QRect(370, 40, 51, 20))
        self.textTrainOursError.setObjectName("textTrainOursError")
        self.labelTrainOursRatioError = QtWidgets.QLabel(Form)
        self.labelTrainOursRatioError.setGeometry(QtCore.QRect(60, 70, 311, 16))
        self.labelTrainOursRatioError.setObjectName("labelTrainOursRatioError")
        self.textTrainRatioError = QtWidgets.QLineEdit(Form)
        self.textTrainRatioError.setGeometry(QtCore.QRect(370, 70, 51, 20))
        self.textTrainRatioError.setObjectName("textTrainRatioError")
        self.labelTrainAvgAcc = QtWidgets.QLabel(Form)
        self.labelTrainAvgAcc.setGeometry(QtCore.QRect(470, 40, 101, 16))
        self.labelTrainAvgAcc.setObjectName("labelTrainAvgAcc")
        self.textTrainAvgAcc = QtWidgets.QLineEdit(Form)
        self.textTrainAvgAcc.setGeometry(QtCore.QRect(570, 40, 51, 20))
        self.textTrainAvgAcc.setObjectName("textTrainAvgAcc")
        self.labelTrainAliensError = QtWidgets.QLabel(Form)
        self.labelTrainAliensError.setGeometry(QtCore.QRect(200, 100, 171, 16))
        self.labelTrainAliensError.setObjectName("labelTrainAliensError")
        self.textTrainAliensError = QtWidgets.QLineEdit(Form)
        self.textTrainAliensError.setGeometry(QtCore.QRect(370, 100, 51, 20))
        self.textTrainAliensError.setObjectName("textTrainAliensError")
        self.labelTrainAliensRatioError = QtWidgets.QLabel(Form)
        self.labelTrainAliensRatioError.setGeometry(QtCore.QRect(70, 130, 291, 16))
        self.labelTrainAliensRatioError.setObjectName("labelTrainAliensRatioError")
        self.textTrainAliensRatioError = QtWidgets.QLineEdit(Form)
        self.textTrainAliensRatioError.setGeometry(QtCore.QRect(370, 130, 51, 20))
        self.textTrainAliensRatioError.setObjectName("textTrainAliensRatioError")
        self.labelTrainHemmingDistance = QtWidgets.QLabel(Form)
        self.labelTrainHemmingDistance.setGeometry(QtCore.QRect(430, 100, 271, 16))
        self.labelTrainHemmingDistance.setObjectName("labelTrainHemmingDistance")
        self.textTrainHemmingDistance = QtWidgets.QLineEdit(Form)
        self.textTrainHemmingDistance.setGeometry(QtCore.QRect(700, 100, 51, 20))
        self.textTrainHemmingDistance.setObjectName("textTrainHemmingDistance")
        self.textTestHemmingDistance = QtWidgets.QLineEdit(Form)
        self.textTestHemmingDistance.setGeometry(QtCore.QRect(700, 260, 51, 20))
        self.textTestHemmingDistance.setObjectName("textTestHemmingDistance")
        self.textTestAliensRatioError = QtWidgets.QLineEdit(Form)
        self.textTestAliensRatioError.setGeometry(QtCore.QRect(370, 290, 51, 20))
        self.textTestAliensRatioError.setObjectName("textTestAliensRatioError")
        self.labelTestAliensError = QtWidgets.QLabel(Form)
        self.labelTestAliensError.setGeometry(QtCore.QRect(200, 260, 171, 16))
        self.labelTestAliensError.setObjectName("labelTestAliensError")
        self.labelTestCountOurs = QtWidgets.QLabel(Form)
        self.labelTestCountOurs.setGeometry(QtCore.QRect(20, 200, 101, 16))
        self.labelTestCountOurs.setObjectName("labelTestCountOurs")
        self.labelTestAvgAcc = QtWidgets.QLabel(Form)
        self.labelTestAvgAcc.setGeometry(QtCore.QRect(470, 200, 101, 16))
        self.labelTestAvgAcc.setObjectName("labelTestAvgAcc")
        self.textTestCountOurs = QtWidgets.QLineEdit(Form)
        self.textTestCountOurs.setGeometry(QtCore.QRect(120, 200, 51, 20))
        self.textTestCountOurs.setObjectName("textTestCountOurs")
        self.textTestCountAliens = QtWidgets.QLineEdit(Form)
        self.textTestCountAliens.setGeometry(QtCore.QRect(120, 260, 51, 20))
        self.textTestCountAliens.setObjectName("textTestCountAliens")
        self.labelTestOursRatioError = QtWidgets.QLabel(Form)
        self.labelTestOursRatioError.setGeometry(QtCore.QRect(60, 230, 311, 16))
        self.labelTestOursRatioError.setObjectName("labelTestOursRatioError")
        self.labelTestAliensRatioError = QtWidgets.QLabel(Form)
        self.labelTestAliensRatioError.setGeometry(QtCore.QRect(70, 290, 291, 16))
        self.labelTestAliensRatioError.setObjectName("labelTestAliensRatioError")
        self.labelTestOursError = QtWidgets.QLabel(Form)
        self.labelTestOursError.setGeometry(QtCore.QRect(190, 200, 181, 16))
        self.labelTestOursError.setObjectName("labelTestOursError")
        self.labelTestCountAliens = QtWidgets.QLabel(Form)
        self.labelTestCountAliens.setGeometry(QtCore.QRect(20, 260, 101, 16))
        self.labelTestCountAliens.setObjectName("labelTestCountAliens")
        self.textTestOursError = QtWidgets.QLineEdit(Form)
        self.textTestOursError.setGeometry(QtCore.QRect(370, 200, 51, 20))
        self.textTestOursError.setObjectName("textTestOursError")
        self.textTestRatioError = QtWidgets.QLineEdit(Form)
        self.textTestRatioError.setGeometry(QtCore.QRect(370, 230, 51, 20))
        self.textTestRatioError.setObjectName("textTestRatioError")
        self.textTestAvgAcc = QtWidgets.QLineEdit(Form)
        self.textTestAvgAcc.setGeometry(QtCore.QRect(570, 200, 51, 20))
        self.textTestAvgAcc.setObjectName("textTestAvgAcc")
        self.labelTestHemmingDistance = QtWidgets.QLabel(Form)
        self.labelTestHemmingDistance.setGeometry(QtCore.QRect(430, 260, 271, 16))
        self.labelTestHemmingDistance.setObjectName("labelTestHemmingDistance")
        self.textTestAliensError = QtWidgets.QLineEdit(Form)
        self.textTestAliensError.setGeometry(QtCore.QRect(370, 260, 51, 20))
        self.textTestAliensError.setObjectName("textTestAliensError")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelTrainTitle.setText(_translate("Form", "Результат на тренировочных данных:"))
        self.labelTrainCount.setText(_translate("Form", "Количество образов:"))
        self.labelTestTitle.setText(_translate("Form", "Результат на тестовых данных:"))
        self.labelTestCount.setText(_translate("Form", "Количество образов:"))
        self.labelTrainCountAliens.setText(_translate("Form", "Количество чужих:"))
        self.labelTrainCountOurs.setText(_translate("Form", "Количество своих:"))
        self.labelTrainOursError.setText(_translate("Form", "Количество ложных срабатывний:"))
        self.labelTrainOursRatioError.setText(_translate("Form", "Отношение ложных срабатываний ко всем \"своим\" образам:"))
        self.labelTrainAvgAcc.setText(_translate("Form", "Средняя точность:"))
        self.labelTrainAliensError.setText(_translate("Form", "Количество ложных пропусков:"))
        self.labelTrainAliensRatioError.setText(_translate("Form", "Отношение ложных пропусков ко всем \"чужим\" образам: "))
        self.labelTrainHemmingDistance.setText(_translate("Form", "Среднее расстояние Хэмминга от истинного ключа:"))
        self.labelTestAliensError.setText(_translate("Form", "Количество ложных пропусков:"))
        self.labelTestCountOurs.setText(_translate("Form", "Количество своих:"))
        self.labelTestAvgAcc.setText(_translate("Form", "Средняя точность:"))
        self.labelTestOursRatioError.setText(_translate("Form", "Отношение ложных срабатываний ко всем \"своим\" образам:"))
        self.labelTestAliensRatioError.setText(_translate("Form", "Отношение ложных пропусков ко всем \"чужим\" образам: "))
        self.labelTestOursError.setText(_translate("Form", "Количество ложных срабатывний:"))
        self.labelTestCountAliens.setText(_translate("Form", "Количество чужих:"))
        self.labelTestHemmingDistance.setText(_translate("Form", "Среднее расстояние Хэмминга от истинного ключа:"))

